// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMAl5xpkEKVYgsfTXMdgLvCVsnJN8hy8A',
    appId: '1:1081677406404:web:8bf386572ffae353a26991',
    messagingSenderId: '1081677406404',
    projectId: 'instagramclone-eb1f6',
    authDomain: 'instagramclone-eb1f6.firebaseapp.com',
    storageBucket: 'instagramclone-eb1f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIDbMHAz10uNfQ3aLc0zwmYPI-FL5ZGvo',
    appId: '1:1081677406404:android:47b3ad6979af5f7ca26991',
    messagingSenderId: '1081677406404',
    projectId: 'instagramclone-eb1f6',
    storageBucket: 'instagramclone-eb1f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLzu5bLlb1KAqunnF4AX4T1bFPJwnb_4c',
    appId: '1:1081677406404:ios:5527b847eb2d1450a26991',
    messagingSenderId: '1081677406404',
    projectId: 'instagramclone-eb1f6',
    storageBucket: 'instagramclone-eb1f6.appspot.com',
    iosBundleId: 'com.example.instragramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLzu5bLlb1KAqunnF4AX4T1bFPJwnb_4c',
    appId: '1:1081677406404:ios:dfe3ce3c1275dd99a26991',
    messagingSenderId: '1081677406404',
    projectId: 'instagramclone-eb1f6',
    storageBucket: 'instagramclone-eb1f6.appspot.com',
    iosBundleId: 'com.example.instragramClone.RunnerTests',
  );
}
